export const LOAD_JOBS = 'LOAD_JOBS';
export const LOAD_JOBS_START = 'LOAD_JOBS_START';
export const LOAD_JOBS_SUCCESS = 'LOAD_JOBS_SUCCESS';
export const LOAD_JOBS_ERROR = 'LOAD_JOBS_ERROR';
export const CLEAR_JOBS= 'CLEAR_JOBS';

export const LOAD_RESOURCE = 'LOAD_RESOURCE';
export const LOAD_RESOURCE_REQUESTED = 'LOAD_RESOURCE_REQUESTED';
export const LOAD_RESOURCE_SUSSCESS = 'LOAD_RESOURCE_SUSSCESS';